Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root  to: 'home#index'
 get '/brands', to: 'home#brands'
 get '/mobiles', to: 'home#mobiles'
 get '/buyers', to: 'home#buyers'
 get '/brands', to: 'home#brands'
 get '/invoices', to: 'home#invoices'
 get '/sellers', to: 'home#sellers'
 get '/mobile/new', to: 'mobile#new'
 get '/brand/new', to: 'brand#new'
 get '/seller/new', to: 'seller#new'
 get '/customer_mobiles', to: 'home#customer_mobiles'

 get '/newmobile', to: 'home#newmobile'
 get '/newbrand', to: 'home#newbrand'
 get '/newbuyer', to: 'home#newbuyer'
 get '/newseller', to: 'home#newseller'
 get '/newinvoice', to: 'home#newinvoice'
 # get '/mobile/edit', to: 'mobile#edit'
 get '/customer_mobiledetails', to: 'home#customer_mobiledetails'
 #get '/seller/new',to:'seller#new'

 post '/create_mobile', to: 'home#create_mobile'
 post '/create_brand', to: 'home#create_brand'
 post '/create_buyer', to: 'home#create_buyer'
 #post '/create_seller', to: 'home#create_seller'
 post '/create_invoice', to: 'home#create_invoice'
 post '/create_customer_mobile', to: 'home#create_customer_mobile'
 post '/create_new_mobile', to: 'mobile#create'
 post '/create_seller', to: 'seller#create'
 post '/create_new_brand', to: 'brand#create'

 delete '/delete_mobile', to: 'home#delete_mobile'
 delete '/delete_customer_mobile', to: 'home#delete_customer_mobile'
 delete '/delete_seller', to: 'home#delete_seller'
 delete '/delete_buyer', to: 'home#delete_er'

 get '/edit_mobile',to:'mobile#edit'
end
